import os

print(os.getcwd())
path = input("Please enter the path\n")
project_name = input("Please enter project name\n")
os.chdir(path)
os.mkdir(project_name)
path = path+"/"+project_name
os.chdir(path)
os.system("git init")
os.mkdir("assets")
print("Assets folder created")
os.mkdir("src")
print("src folder created")
myfile = open("README.md","w")
myfile.write(f"## {project_name}")
myfile.close()
print("README file created")
myfile = open("requirements.txt","w")
myfile.close()
print("requirements file created")
myfile = open(".gitignore","w")
myfile.close()
print("gitignore file created")
path = path+"/src"
os.chdir(path)
myfile = open(f"{project_name}.py","w")
myfile.close()
print(f"{project_name}.py file created")
print("All Done!")